services:
  - type: web
    name: personal-trainer-api
    env: node
    buildCommand: npm install && cd client && npm install && CI=false npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DOMAIN
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: API_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: personal-trainer-db
          property: connectionString

databases:
  - name: personal-trainer-db
    plan: free
    databaseName: fitbooking
    user: fitbooking_user

